Update delete.yml

diff --git a/.github/workflows/delete.yml b/.github/workflows/delete.yml
--- a/.github/workflows/delete.yml
+++ b/.github/workflows/delete.yml
@@ -43,19 +43,25 @@ jobs:
           SECURITY_GROUP_ID=$(aws elbv2 describe-load-balancers --load-balancer-arns "$ALB_ARN" --query 'LoadBalancers[0].SecurityGroups[0]' --output text)
           echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV
 
-      - name: Delete Security Group Ingress for All Listener Ports
+      - name: Get Existing Security Group Ingress Rules
+        id: get-ingress-rules
+        run: |
+          SECURITY_GROUP_ID="${{ env.SECURITY_GROUP_ID }}"
+          INGRESS_RULES=$(aws ec2 describe-security-groups --group-ids "$SECURITY_GROUP_ID" --query "SecurityGroups[0].IpPermissions[?FromPort>=0].{FromPort:FromPort, ToPort:ToPort, IpProtocol:IpProtocol}" --output json)
+          echo "INGRESS_RULES=$INGRESS_RULES" >> $GITHUB_ENV
+
+      - name: Revoke Security Group Ingress for Listener Ports
         run: |
           SECURITY_GROUP_ID="${{ env.SECURITY_GROUP_ID }}"
           LISTENERS="${{ env.LISTENERS }}"
-          PORTS=$(aws elbv2 describe-listeners --listener-arns $LISTENERS --query 'Listeners[*].Port' --output text)
 
-          if [ "$SECURITY_GROUP_ID" != "None" ]; then
-            for PORT in $PORTS; do
-              aws ec2 revoke-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port "$PORT" --cidr 0.0.0.0/0 || echo "Ingress rule for port $PORT not found."
-            done
-          else
-            echo "No Security Group found for the ALB."
-          fi
+          for LISTENER in $LISTENERS; do
+            LISTENER_PORT=$(aws elbv2 describe-listeners --listener-arn "$LISTENER" --query 'Listeners[0].Port' --output text)
+            echo "Revoking ingress for port $LISTENER_PORT"
+
+            # Revoke the ingress rule for this port
+            aws ec2 revoke-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port "$LISTENER_PORT" --cidr 0.0.0.0/0 || echo "Ingress rule for port $LISTENER_PORT not found."
+          done
 
       - name: Delete Listeners
         run: |
