Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -177,20 +177,22 @@ jobs:
             echo "LISTENER_ARN=${LISTENER_ARN}" >> $GITHUB_ENV
           fi
       
-      - name: Create Listener if None Exists
+      - name: Create New Listener
         run: |
-          if [ "${{ env.LISTENER_ARN }}" == "None" ]; then
-            LISTENER_ARN=$(aws elbv2 create-listener \
-              --load-balancer-arn "arn:aws:elasticloadbalancing:eu-north-1:851725362124:loadbalancer/app/alb/a1ca35f7a5775050" \
-              --protocol HTTP \
-              --port 8000 \
-              --default-actions Type=forward,TargetGroupArn=$TARGET_GROUP_ARN \
-              --query 'Listeners[0].ListenerArn' \
-              --output text)
+          LISTENER_ARN=$(aws elbv2 create-listener \
+            --load-balancer-arn "arn:aws:elasticloadbalancing:eu-north-1:851725362124:loadbalancer/app/alb/a1ca35f7a5775050" \
+            --protocol HTTP \
+            --port 8000 \
+            --default-actions Type=forward,TargetGroupArn=$TARGET_GROUP_ARN \
+            --query 'Listeners[0].ListenerArn' \
+            --output text)
+            
+          if [ $? -eq 0 ]; then
             echo "Created new listener: ${LISTENER_ARN}"
           else
-            echo "Existing listener found: ${LISTENER_ARN}"
+            echo "Failed to create listener."
           fi
+
       
       - name: Register Targets
         run: |
